blog/src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffreRepository::class)
 */
class Offre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_update;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fin_mission;

    /**
     * @ORM\ManyToOne(targetEntity=Contrat::class, inversedBy="relation")
     */
    private $contrat;

    /**
     * @ORM\ManyToOne(targetEntity=Typecontrat::class, inversedBy="relation")
     */
    private $typecontrat;



    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(?\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getFinMission(): ?\DateTimeInterface
    {
        return $this->fin_mission;
    }

    public function setFinMission(?\DateTimeInterface $fin_mission): self
    {
        $this->fin_mission = $fin_mission;

        return $this;
    }

    public function getContrat(): ?Contrat
    {
        return $this->contrat;
    }

    public function setContrat(?Contrat $contrat): self
    {
        $this->contrat = $contrat;

        return $this;
    }

    public function getTypecontrat(): ?Typecontrat
    {
        return $this->typecontrat;
    }

    public function setTypecontrat(?Typecontrat $typecontrat): self
    {
        $this->typecontrat = $typecontrat;

        return $this;
    }
    /**
        * Transform to string
        * @return string
    */
    public function __toString()
    {
        return $this->Title;
        return $this->Contrat;
        return $this->Description;
        return $this->Adresse;
        return $this->TypeContrat;
        
    }
}

blog/src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Entity\Offre;
use App\Entity\Typecontrat;
use App\Repository\OffreRepository;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class BlogController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('blog/index.html.twig', [
            
        ]);
    }
    /**
     * @Route("/article", name="article_list")
     */
    public function list(OffreRepository $ripo): Response
    {
        $offre = $ripo->findAll();


        return $this->render('blog/article.html.twig', [
            'offre' => $offre,
        ]);
    }

    /**
     * @Route("/article/{id}",name="offre.show")
     */
    public function show(Offre $offres, Request $request)
    {
        // dd($request->get('id'));

        return $this->render('blog/offre.html.twig', [
            'offres' => $offres,
        ]);
    }

    /**
     * @Route("/create", name="offers.create")
     */
    public function create(Request $request, EntityManagerInterface $em) {
        
        $offre = new Offre();

        $form = $this->createFormBuilder($offre)
            ->add("Title", TextType::class, [
                "label" => "Titre du job : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez le nom du job",
                ]
            ])
            ->add('contrat', EntityType::class, [
                "label" => "Contrat : ",
                "class" => Contrat::class,
                "attr" => [
                    "class" => "sectionForm--select",
                    "onchange" => "isChecked()"
                ],
            ])
            ->add('typeContrat', EntityType::class, [
                "label" => "Type du contrat : ",
                "class" => TypeContrat::class,
                "attr" => [
                    "class" => "sectionForm--select",
                ],
            ])
           ->add('fin_mission', DateType::class, [
                "label" => "Fin de la mission : ",
                "label_attr" => [
                    "id" => "label"
                ],
                "attr" => [
                    "class" => "sectionForm--date",
                ]
            ])         
            ->add("Description", TextareaType::class, [
                "label" => "Description du job : ",
                "attr" => [
                    "class" => "sectionForm--text"
                ]
            ])
            ->add("Adresse", TextType::class, [
                "label" => "Adresse : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez l'adresse",
                ]
            ])
            ->add("Code_postal", TextType::class, [
                "label" => "Code postal : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez le code postal",
                ]
            ])
            ->add("Submit", SubmitType::class, [
                "attr" => [
                    "class" => "sectionForm--btn"
                ]
            ])
            ->getForm();

        $offre->setDateCreation(new \DateTime());

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $em->persist($offre);
            $em->flush();
            $this->addFlash('success', 'Votre offre a bien été publié, merci !');
            return $this->redirectToRoute('home');
        }

        return $this->render('blog/create.html.twig', [
            'form' => $form->createView()
        ]);

    }
}

blog/templates/blog/article.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="sectionArticle">
            {% for offre in offre %}
            <a href="/article/{{offre.id}}"
                <div class="sectionArticle__container">
                    <div class="sectionArticle__container--first">
                        <div class="sectionArticle__container--first--left">
                            <p class="sectionArticle__container--first--left--contrat">{{offre.contrat}}, {{offre.typecontrat}}</p>
                            <img class="sectionArticle__container--first--left--img" src="/build/images/perso_icon.png" alt="une icone de personne">
                        </div>
                        <div class="sectionArticle__container--first--right">
                        </div>
                    </div>
                    <div class="sectionArticle__container--second">
                        <div class="sectionArticle__container--second--right">
                            <p class="sectionArticle__container--second--right--title">{{offre.title}}</p>
                            <p class="sectionArticle__container--second--right--dateCreation">Créé le : {{offre.dateCreation |date("d/m/Y")}}</p>
                            <p class="sectionArticle__container--second--right--adresse">{{offre.adresse}}, {{offre.codePostal}}</p>
                        </div>
                        <div class="sectionArticle__container--second--left">
                            <p class="sectionArticle__container--second--left--description">{{offre.description}}</p>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
    </section>
{% endblock %}

blog/templates/blog/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if app.user %}
    <section class="sectionForm">
        <div class="sectionForm--container">
            {{ form_start(form) }}
                <div class="sectionForm__form--container">
                    {{ form_row(form.Title) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.contrat) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.typeContrat) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.fin_mission) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Description) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Adresse) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Code_postal) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Submit) }}
                </div>
            {{ form_end(form) }}
        </div>
    </section>
    {% else %}
    <section class="sectionRefus">
        <div class="sectionRefus--container">
            <p class="sectionRefus--text">Veuillez vous connecter.</p>
        </div>
    </section>
    {% endif %}
    <script>
    function isChecked(){
        let select = document.getElementById("form_contrat");
        let select_2 = select.options[select.selectedIndex];
        if(select_2.innerHTML === "CDI") {
            document.getElementById("form_fin_mission").style.display = "none";
            document.getElementById("label").style.display = "none";
        } else {
            document.getElementById("form_fin_mission").style.display = "block";
            document.getElementById("label").style.display = "block";
        }
     }
    </script>
{% endblock %}

blog/templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="sectionAccueil">
        <div class="sectionAccueil__container">
            <p class="sectionAccueil__text">Trouvez le travail de vos rêves !</p>
            <a href="/article" class="sectionAccueil__lien">Je change de vie !</a>
        </div>
    </section>
{% endblock %}

blog/templates/blog/offre.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="sectionArticle">
                <div class="sectionArticle__container">
                    <div class="sectionArticle__container--first">
                        <div class="sectionArticle__container--first--left">
                            <p class="sectionArticle__container--first--left--contrat">{{offres.contrat}}, {{offres.typecontrat}}</p>
                            <img class="sectionArticle__container--first--left--img" src="/build/images/perso_icon.png" alt="une icone de personne">
                        </div>
                        <div class="sectionArticle__container--first--right">
                        </div>
                    </div>
                    <div class="sectionArticle__container--second">
                        <div class="sectionArticle__container--second--right">
                            <p class="sectionArticle__container--second--right--title">{{offres.title}}</p>
                            <p class="sectionArticle__container--second--right--dateCreation">Créé le : {{offres.dateCreation |date("d/m/Y")}}</p>
                            <p class="sectionArticle__container--second--right--dateCreation">Modifié le : {{offres.dateUpdate |date("d/m/Y")}}</p>
                            <p class="sectionArticle__container--second--right--dateCreation">Fin de contrat (si CDD ou Free) : {{offres.finMission |date("d/m/Y")}}</p>
                            <p class="sectionArticle__container--second--right--adresse">{{offres.adresse}}, {{offres.codePostal}}</p>
                        </div>
                        <div class="sectionArticle__container--second--left">
                            <p class="sectionArticle__container--second--left--description">{{offres.description}}</p>
                        </div>
                    </div>
                </div>
    </section>
{% endblock %}