blog/src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffreRepository::class)
 */
class Offre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_update;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fin_mission;

    /**
     * @ORM\ManyToOne(targetEntity=Contrat::class, inversedBy="relation")
     */
    private $contrat;

    /**
     * @ORM\ManyToOne(targetEntity=Typecontrat::class, inversedBy="relation")
     */
    private $typecontrat;



    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(?\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getFinMission(): ?\DateTimeInterface
    {
        return $this->fin_mission;
    }

    public function setFinMission(?\DateTimeInterface $fin_mission): self
    {
        $this->fin_mission = $fin_mission;

        return $this;
    }

    public function getContrat(): ?Contrat
    {
        return $this->contrat;
    }

    public function setContrat(?Contrat $contrat): self
    {
        $this->contrat = $contrat;

        return $this;
    }

    public function getTypecontrat(): ?Typecontrat
    {
        return $this->typecontrat;
    }

    public function setTypecontrat(?Typecontrat $typecontrat): self
    {
        $this->typecontrat = $typecontrat;

        return $this;
    }
    /**
        * Transform to string
        * @return string
    */
    public function __toString()
    {
        return $this->Title;
        return $this->Contrat;
        return $this->Description;
        return $this->Adresse;
        return $this->TypeContrat;
        
    }
}

blog/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Contrat;
use App\Entity\Typecontrat;
use App\Entity\Offre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Repository\OffreRepository;


class SecurityController extends AbstractController
{
    /**
     * @Route("/register", name="register")
     */
    public function register(Request $request, EntityManagerInterface $em, UserPasswordEncoderInterface $passwordEncoder)
    {

        $user = new User();

        $form = $this->createFormBuilder($user)
            ->add("Username", TextType::class, [
                "label" => "Pseudonyme : ",
                "attr" => [
                    "class" => "sectionRegister--text",
                    "placeholder" => "Entrez votre pseudo",
                ]
            ])
            ->add("firstName", TextType::class, [
                "label" => "Prénom : ",
                "attr" => [
                    "class" => "sectionRegister--text",
                    "placeholder" => "Prénom",
                ]
            ])
            ->add("lastName", TextType::class, [
                "label" => "Nom de famille : ",
                "attr" => [
                    "class" => "sectionRegister--text",
                    "placeholder" => "Nom de famille",
                ]
            ])
            ->add("email", EmailType::class, [
                "label" => "E-mail : ",
                "attr" => [
                    "class" => "sectionRegister--text",
                    "placeholder" => "E-mail",
                ]
            ])
            ->add("password", PasswordType::class, [
                "label" => "Mot de passe : ",
                "attr" => [
                    "class" => "sectionRegister--text",
                    "placeholder" => "Mot de passe",
                ]
                //encode password
            ])
            ->add("Submit", SubmitType::class, [
                "attr" => [
                    "class" => "sectionRegister--btn"
                ]
            ])
            ->getForm();

            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()) {
                $hash = $passwordEncoder->encodePassword($user, $user->getPassword()); 
                $user->setPassword($hash);
                $em->persist($user);
                $em->flush();
                $this->addFlash('success', 'Votre compte a bien été créé.');
                return $this->redirectToRoute('home');
            }

        return $this->render('security/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/connexion", name="connexion")
     */
    public function connexion(AuthenticationUtils $authenticationUtils)
    {

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/connexion.html.twig', [
            'last_username' => $lastUsername,
           'error'         => $error,
        ]);
    }

    /**
     * @Route("/tableau", name="tableau")
     */
    public function crud(OffreRepository $ripo): Response
    {
        $offre = $ripo->findAll();

        return $this->render('security/tableau.html.twig', [
            'offre' => $offre,
        ]);
    }

    /**
        * @Route("/modifier/{id}", name="modifier")
    */
    public function modifier(Request $request, EntityManagerInterface $em, Offre $offre, $id): Response
    {

        $offre = $em->getRepository('App\Entity\Offre')->find($id);
        $form = $this->createFormBuilder($offre)
            ->add("Title", TextType::class, [
                "label" => "Titre du job : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez le nom du job",
                ]
            ])
            ->add('contrat', EntityType::class, [
                "label" => "Contrat : ",
                "class" => Contrat::class,
                "attr" => [
                    "class" => "sectionForm--select",
                    "onchange" => "isChecked()"
                ],
            ])
            ->add('typeContrat', EntityType::class, [
                "label" => "Type du contrat : ",
                "class" => TypeContrat::class,
                "attr" => [
                    "class" => "sectionForm--select",
                ],
            ])
           ->add('fin_mission', DateType::class, [
                "label" => "Fin de la mission : ",
                "label_attr" => [
                    "id" => "label"
                ],
                "attr" => [
                    "class" => "sectionForm--date",
                ]
            ])         
            ->add("Description", TextareaType::class, [
                "label" => "Description du job : ",
                "attr" => [
                    "class" => "sectionForm--text"
                ]
            ])
            ->add("Adresse", TextType::class, [
                "label" => "Adresse : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez l'adresse",
                ]
            ])
            ->add("Code_postal", TextType::class, [
                "label" => "Code postal : ",
                "attr" => [
                    "class" => "sectionForm--text",
                    "placeholder" => "Entrez le code postal",
                ]
            ])
            ->add("Submit", SubmitType::class, [
                "attr" => [
                    "class" => "sectionForm--btn"
                ]
            ])
            ->getForm();

            $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offre = $form->getData();
            $em->persist($offre);
            $em->flush();
            $this->addFlash('success', 'Votre offre a bien été modifié, merci !');
            return $this->redirectToRoute('home');
        }
    
        return $this->render("security/modifier.html.twig", [
            "form" => $form->createView(),
        ]);
    }
    /**
        * @Route("/delete/{id}", name="delete")
    */
    public function delete(Request $request, EntityManagerInterface $em, Offre $offre, $id): Response
    {

        $offre = $em->getRepository('App\Entity\Offre')->find($id);
        $em->remove($offre);
        $em->flush();
        $this->addFlash('success', 'Votre offre a bien été supprimé, merci !');
        return $this->redirectToRoute("home");
    }
}

blog/templates/security/connexion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion{% endblock %}

{% block body %}

{% if app.user %}
    <section class="sectionRefus">
        <div class="sectionRefus--container">
            <p class="sectionRefus--text">Vous êtes déjà connecté !</p>
        </div>
    </section>
{% else %}
    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}
    <section class="sectionForm">
        <div class="sectionForm--container sectionForm--container--third">
            
            <form action="{{ path('connexion') }}" method="post">
            <p class="sectionForm--connect">Connexion<p>
                <div class="sectionForm__form--container">
                    <div>
                        <label for="username">E-mail:</label>
                        <input type="text" id="username" name="_username" value="{{ last_username }}" />
                    </div>
                </div>
                
                <div class="sectionForm__form--container">
                    <div>
                        <label for="password">Mot de passe :</label>
                        <input type="password" id="password" name="_password" />
                    </div>
                </div>


                <input type="hidden" name="_target_path" value="/" />
                <div class="sectionForm__form--container">
                    <div>
                        <button type="submit">Connexion</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endif %}

{% endblock %}

blog/templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}S'inscrire{% endblock %}

{% block body %}

    {% if app.user %}
        <section class="sectionRefus">
            <div class="sectionRefus--container">
                <p class="sectionRefus--text">Vous êtes déjà connecté !</p>
            </div>
        </section>
    {% else %}
    <section class="sectionForm">
        <div class="sectionForm--container--second sectionForm--container">
            {{ form_start(form) }}
                <div class="sectionForm__form--container">
                    {{ form_row(form.Username) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.firstName) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.lastName) }}
                </div>
                <div class="sectionForm__form--container">
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form.email) }}
                </div>
                    {{ form_row(form.email) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.password) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Submit) }}
                </div>
            {{ form_end(form) }}
        </div>
    </section>

    {% endif %}
{% endblock %}

blog/templates/security/modifier.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if app.user %}
    <section class="sectionForm">
        <div class="sectionForm--container">
            {{ form_start(form) }}
                <div class="sectionForm__form--container">
                    {{ form_row(form.Title) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.contrat) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.typeContrat) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.fin_mission) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Description) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Adresse) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Code_postal) }}
                </div>
                <div class="sectionForm__form--container">
                    {{ form_row(form.Submit) }}
                </div>
            {{ form_end(form) }}
        </div>
    </section>
     {% else %}
    <section class="sectionRefus">
        <div class="sectionRefus--container">
            <p class="sectionRefus--text">Veuillez vous connecter.</p>
        </div>
    </section>
    {% endif %}
    <script>
    function isChecked(){
        let select = document.getElementById("form_contrat");
        let select_2 = select.options[select.selectedIndex];
        if(select_2.innerHTML === "CDI") {
            document.getElementById("form_fin_mission").style.display = "none";
            document.getElementById("label").style.display = "none";
        } else {
            document.getElementById("form_fin_mission").style.display = "block";
            document.getElementById("label").style.display = "block";
        }
     }
    </script>

{% endblock %}

blog/templates/security/tableau.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}

    {% if app.user %}
        <section class="sectionTab">
            <div class="sectionTab__container">
                <a class="sectionTab--link" href="/create">Ajouter mon offre</a>
                {% for offre in offre %}
                <div class="sectionTab--offre__container">
                    <p class="sectionTab--offre__title">{{offre.title}}</p>
                    <p class="sectionTab--offre__date">Créé le : {{offre.dateCreation |date("d/m/Y")}}</p>
                    <a href="modifier/{{offre.id}}" class="sectionTab--offre__modif">Modifier</a>
                    <a href="delete/{{offre.id}}" class="sectionTab--offre__delete">Supprimer</a>
                </div>
                {% endfor %}
            </div>
        </section>
    {% else %}
    <section class="sectionRefus">
        <div class="sectionRefus--container">
            <p class="sectionRefus--text">Veuillez vous connecter.</p>
        </div>
    </section>
    {% endif %}

{% endblock %}